server:
  port: 9898
  servlet:
    context-path: /

spring:
  application:
    name: springcache-redis
  redis:
    host: 127.0.0.1
    port: 6379
    password:  #Redis服务器连接密码（默认为空）
    timeout: 30000 #连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 20 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
  cache:
    type: redis
    #redis:
    #  time-to-live: 3600000 #设置缓存过期时间
    #  key-prefix: CACHE_ #指定默认前缀，如果此处我们指定了前缀则使用我们指定的前缀，推荐此处不指定前缀
    #  cache-null-values: true #是否缓存空值，防止缓存穿透

